name: ðŸªž Mirror

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/G-EIP-700-PAR-7-1-eip-emil.pedersen.git"

on: push

jobs:
  push_to_mirror:
    name: "Push code to the mirror repository"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - uses: "pixta-dev/repository-mirroring-action@v1"
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
